export const NEW_PACKAGE_BOOKING_REQUEST = "NEW_PACKAGE_BOOKING_REQUEST";
export const NEW_PACKAGE_BOOKING_SUCCESS = "NEW_PACKAGE_BOOKING_SUCCESS";
export const NEW_PACKAGE_BOOKING_FAIL = "NEW_PACKAGE_BOOKING_FAIL";

export const MY_PACKAGE_REQUEST = "MY_PACKAGE_REQUEST";
export const MY_PACKAGE_SUCCESS = "MY_PACKAGE_SUCCESS";
export const MY_PACKAGE_FAIL = "MY_PACKAGE_FAIL";

export const PACKAGE_DETAILS_REQUEST = "PACKAGE_DETAILS_REQUEST";
export const PACKAGE_DETAILS_SUCCESS = "PACKAGE_DETAILS_SUCCESS";
export const PACKAGE_DETAILS_FAIL = "PACKAGE_DETAILS_FAIL";

export const ALL_PACKAGES_REQUEST = "ALL_PACKAGES_REQUEST";
export const ALL_PACKAGES_SUCCESS = "ALL_PACKAGES_SUCCESS";
export const ALL_PACKAGES_FAIL = "ALL_PACKAGES_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
