export const NEW_HOTEL_BOOKING_REQUEST = "NEW_HOTEL_BOOKING_REQUEST";
export const NEW_HOTEL_BOOKING_SUCCESS = "NEW_HOTEL_BOOKING_SUCCESS";
export const NEW_HOTEL_BOOKING_FAIL = "NEW_HOTEL_BOOKING_FAIL";

export const MY_HOTEL_REQUEST = "MY_HOTEL_REQUEST";
export const MY_HOTEL_SUCCESS = "MY_HOTEL_SUCCESS";
export const MY_HOTEL_FAIL = "MY_HOTEL_FAIL";

export const HOTEL_DETAILS_REQUEST = "HOTEL_DETAILS_REQUEST";
export const HOTEL_DETAILS_SUCCESS = "HOTEL_DETAILS_SUCCESS";
export const HOTEL_DETAILS_FAIL = "HOTEL_DETAILS_FAIL";


export const CLEAR_ERRORS = "CLEAR_ERRORS";
