export const NEW_CAR_BOOKING_REQUEST = "NEW_CAR_BOOKING_REQUEST";
export const NEW_CAR_BOOKING_SUCCESS = "NEW_CAR_BOOKING_SUCCESS";
export const NEW_CAR_BOOKING_FAIL = "NEW_CAR_BOOKING_FAIL";

export const MY_CAR_REQUEST = "MY_CAR_REQUEST";
export const MY_CAR_SUCCESS = "MY_CAR_SUCCESS";
export const MY_CAR_FAIL = "MY_CAR_FAIL";

export const CAR_DETAILS_REQUEST = "CAR_DETAILS_REQUEST";
export const CAR_DETAILS_SUCCESS = "CAR_DETAILS_SUCCESS";
export const CAR_DETAILS_FAIL = "CAR_DETAILS_FAIL";

export const ALL_CARS_REQUEST = "ALL_CARS_REQUEST";
export const ALL_CARS_SUCCESS = "ALL_CARS_SUCCESS";
export const ALL_CARS_FAIL = "ALL_CARS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
