export const ADMIN_REGISTER_REQUEST = "ADMIN_REGISTER_REQUEST";
export const ADMIN_REGISTER_SUCCESS = "ADMIN_REGISTER_SUCCESS";
export const ADMIN_REGISTER_FAIL = "ADMIN_REGISTER_FAIL";
export const ALL_ADMIN_REQUEST = "ALL_ADMIN_REQUEST";
export const ALL_ADMIN_SUCCESS = "ALL_ADMIN_SUCCESS";
export const ALL_ADMIN_FAIL = "ALL_ADMIN_FAIL";
