export const ALL_BOOKED_CARS_REQUEST = "ALL_BOOKED_CARS_REQUEST";
export const ALL_BOOKED_CARS_SUCCESS = "ALL_BOOKED_CARS_SUCCESS";
export const ALL_BOOKED_CARS_FAIL = "ALL_BOOKED_CARS_FAIL";

export const GET_BOOKED_CAR_DETAIL_REQUEST = "GET_BOOKED_CAR_DETAIL_REQUEST";
export const GET_BOOKED_CAR_DETAIL_SUCCESS = "GET_BOOKED_CAR_DETAIL_SUCCESS";
export const GET_BOOKED_CAR_DETAIL_FAIL = "GET_BOOKED_CAR_DETAIL_FAIL";

export const DELETE_BOOKED_CAR_REQUEST = "DELETE_BOOKED_CAR_REQUEST";
export const DELETE_BOOKED_CAR_SUCCESS = "DELETE_BOOKED_CAR_SUCCESS";
export const DELETE_BOOKED_CAR_FAIL = "DELETE_BOOKED_CAR_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
