export const ALL_BOOKED_HOTELS_REQUEST = "ALL_BOOKED_HOTELS_REQUEST";
export const ALL_BOOKED_HOTELS_SUCCESS = "ALL_BOOKED_HOTELS_SUCCESS";
export const ALL_BOOKED_HOTELS_FAIL = "ALL_BOOKED_HOTELS_FAIL";

export const GET_BOOKED_HOTEL_DETAIL_REQUEST =
  "GET_BOOKED_HOTEL_DETAIL_REQUEST";
export const GET_BOOKED_HOTEL_DETAIL_SUCCESS =
  "GET_BOOKED_HOTEL_DETAIL_SUCCESS";
export const GET_BOOKED_HOTEL_DETAIL_FAIL = "GET_BOOKED_HOTEL_DETAIL_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
