export const ALL_BOOKED_PACKAGES_REQUEST = "ALL_BOOKED_PACKAGES_REQUEST";
export const ALL_BOOKED_PACKAGES_SUCCESS = "ALL_BOOKED_PACKAGES_SUCCESS";
export const ALL_BOOKED_PACKAGES_FAIL = "ALL_BOOKED_PACKAGES_FAIL";

export const GET_BOOKED_PACKAGE_DETAIL_REQUEST =
  "GET_BOOKED_PACKAGE_DETAIL_REQUEST";
export const GET_BOOKED_PACKAGE_DETAIL_SUCCESS =
  "GET_BOOKED_PACKAGE_DETAIL_SUCCESS";
export const GET_BOOKED_PACKAGE_DETAIL_FAIL = "GET_BOOKED_PACKAGE_DETAIL_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
