export const CREATE_NEW_HOTEL_REQUEST = "CREATE_NEW_HOTEL_REQUEST";
export const CREATE_NEW_HOTEL_SUCCESS = "CREATE_NEW_HOTEL_SUCCESS";
export const CREATE_NEW_HOTEL_FAIL = "CREATE_NEW_HOTEL_FAIL";
export const CREATE_NEW_HOTEL_RESET = "CREATE_NEW_HOTEL_RESET";
export const GET_ALL_HOTELS_REQUEST = "GET_ALL_HOTELS_REQUEST";
export const GET_ALL_HOTELS_SUCCESS = "GET_ALL_HOTELS_SUCCESS";
export const GET_ALL_HOTELS_FAIL = "GET_ALL_HOTELS_FAIL";
export const GET_HOTEL_BY_SLUG_REQUEST = "GET_HOTEL_BY_SLUG_REQUEST";
export const GET_HOTEL_BY_SLUG_SUCCESS = "GET_HOTEL_BY_SLUG_SUCCESS";
export const GET_HOTEL_BY_SLUG_FAIL = "GET_HOTEL_BY_SLUG_FAIL";
export const GET_TOP_DES_HOTEL_BY_SLUG_REQUEST =
  "GET_TOP_DES_HOTEL_BY_SLUG_REQUEST";
export const GET_TOP_DES_HOTEL_BY_SLUG_SUCCESS =
  "GET_TOP_DES_HOTEL_BY_SLUG_SUCCESS";
export const GET_TOP_DES_HOTEL_BY_SLUG_FAIL = "GET_TOP_DES_HOTEL_BY_SLUG_FAIL";
export const DELETE_HOTEL_REQUEST = "DELETE_HOTEL_REQUEST";
export const DELETE_HOTEL_SUCCESS = "DELETE_HOTEL_SUCCESS";
export const DELETE_HOTEL_FAIL = "DELETE_HOTEL_FAIL";
export const DELETE_HOTEL_RESET = "DELETE_HOTEL_RESET";
export const GET_HOTEL_DETAILS_REQUEST = "GET_HOTEL_DETAILS_REQUEST";
export const GET_HOTEL_DETAILS_SUCCESS = "GET_HOTEL_DETAILS_SUCCESS";
export const GET_HOTEL_DETAILS_FAIL = "GET_HOTEL_DETAILS_FAIL";
