export const GET_ALL_VACATION_CATEGORIES_REQUEST =
  "GET_ALL_VACATION_CATEGORIES_REQUEST";
export const GET_ALL_VACATION_CATEGORIES_SUCCESS =
  "GET_ALL_VACATION_CATEGORIES_SUCCESS";
export const GET_ALL_VACATION_CATEGORIES_FAIL =
  "GET_ALL_VACATION_CATEGORIES_FAIL";
export const CREATE_NEW_CATEGORY_REQUEST = "CREATE_NEW_CATEGORY_REQUEST";
export const CREATE_NEW_CATEGORY_SUCCESS = "CREATE_NEW_CATEGORY_SUCCESS";
export const CREATE_NEW_CATEGORY_FAIL = "CREATE_NEW_CATEGORY_FAIL";
export const DELETE_VACATION_CATEGORY_REQUEST =
  "DELETE_VACATION_CATEGORY_REQUEST";
export const DELETE_VACATION_CATEGORY_SUCCESS =
  "DELETE_VACATION_CATEGORY_SUCCESS";
export const DELETE_VACATION_CATEGORY_FAIL = "DELETE_VACATION_CATEGORY_FAIL";
export const UPDATE_VACATION_CATEGORY_REQUEST =
  "UPDATE_VACATION_CATEGORY_REQUEST";
export const UPDATE_VACATION_CATEGORY_SUCCESS =
  "UPDATE_VACATION_CATEGORY_SUCCESS";
export const UPDATE_VACATION_CATEGORY_FAIL = "UPDATE_VACATION_CATEGORY_FAIL";
